// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// create_lexicon
Rcpp::List create_lexicon(arma::imat& Cd, const arma::mat& Phi, arma::sp_mat& dtm, const arma::vec alpha, const bool freeze_topics, const int threads);
RcppExport SEXP _tidylda_create_lexicon(SEXP CdSEXP, SEXP PhiSEXP, SEXP dtmSEXP, SEXP alphaSEXP, SEXP freeze_topicsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat& >::type Cd(CdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const bool >::type freeze_topics(freeze_topicsSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_lexicon(Cd, Phi, dtm, alpha, freeze_topics, threads));
    return rcpp_result_gen;
END_RCPP
}
// fit_lda_c
Rcpp::List fit_lda_c(const std::vector<std::vector<int>>& docs, const int Nk, const arma::mat& beta, arma::vec& alpha, arma::umat& Cd, arma::mat& Cv, arma::uvec& Ck, std::vector<std::vector<int>>& Zd, const arma::mat& Phi, const int iterations, const int burnin, const bool freeze_topics, const bool calc_likelihood, const bool optimize_alpha);
RcppExport SEXP _tidylda_fit_lda_c(SEXP docsSEXP, SEXP NkSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP CdSEXP, SEXP CvSEXP, SEXP CkSEXP, SEXP ZdSEXP, SEXP PhiSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP freeze_topicsSEXP, SEXP calc_likelihoodSEXP, SEXP optimize_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type docs(docsSEXP);
    Rcpp::traits::input_parameter< const int >::type Nk(NkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type Cd(CdSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Cv(CvSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type Ck(CkSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int>>& >::type Zd(ZdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const bool >::type freeze_topics(freeze_topicsSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_likelihood(calc_likelihoodSEXP);
    Rcpp::traits::input_parameter< const bool >::type optimize_alpha(optimize_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_lda_c(docs, Nk, beta, alpha, Cd, Cv, Ck, Zd, Phi, iterations, burnin, freeze_topics, calc_likelihood, optimize_alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidylda_create_lexicon", (DL_FUNC) &_tidylda_create_lexicon, 6},
    {"_tidylda_fit_lda_c", (DL_FUNC) &_tidylda_fit_lda_c, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidylda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
